# package_assets: always # To test this in development

embed_assets: on

# No javascript template pre-compiler
template_function: off


javascripts:
  shared:
    - public/javascripts/jquery.hoverIntent.minified.js
    - public/javascripts/pubsub.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/jquery.placeholder.js
    - public/javascripts/compiled/modal.js
    - public/javascripts/compiled/dreamplugs.js
    - public/javascripts/compiled/application.js

  entries:
    - public/javascripts/geo.js
    - public/javascripts/dreams.js
    - public/javascripts/compiled/follow_hover.js
    - public/javascripts/compiled/dreamfield.js
    - public/javascripts/tag_stream.js
    
stylesheets:
  shared:
    - public/stylesheets/compiled/shared.css
    - public/stylesheets/jquery.lightbox-0.5.css