# package_assets: always # To test this in development

embed_assets: datauri

# No javascript template pre-compiler
template_function: off


javascripts:

  jmvc_plugins:
    - public/jquery/jquery.js
    - public/compiled/steal_proxy.js
    - public/jquery/class/class.js
    - public/jquery/lang/lang.js
    - public/jquery/event/destroyed/destroyed.js
    - public/jquery/controller/controller.js
    - public/jquery/lang/openajax/openajax.js
    - public/jquery/controller/subscribe/subscribe.js
    - public/jquery/event/hashchange/hashchange.js
    - public/jquery/controller/history/history.js
    - public/jquery/view/view.js
    - public/jquery/lang/rsplit/rsplit.js
    - public/jquery/view/ejs/ejs.js
    - public/jquery/controller/view/view.js
    - public/jquery/model/model.js
    - public/jquery/dom/dom.js
    - public/jquery/dom/fixture/fixture.js
    - public/jquery/dom/form_params/form_params.js
  
  jmvc_resources:
    - public/compiled/resources/ui/jquery.ui.core.js
    - public/compiled/resources/ui/jquery.ui.widget.js
    - public/compiled/resources/ui/jquery.ui.mouse.js
    - public/compiled/resources/ui/jquery.ui.position.js
    - public/compiled/resources/ui/jquery.ui.selectmenu.js
    - public/compiled/resources/ui/jquery.ui.draggable.js
    - public/compiled/resources/ui/jquery.ui.droppable.js
    - public/compiled/resources/*.js

      
  dreamcatcher_app:
    - public/compiled/models/**/*.js
    - public/compiled/classes/*.js
    # - public/compiled/controllers/**/*.js
    - public/compiled/controllers/application_controller.js
    - public/compiled/controllers/common/upload_controller.js
    - public/compiled/controllers/common/tags_controller.js
    - public/compiled/controllers/common/comments_controller.js
    - public/compiled/controllers/users/meta_menu_controller.js
    - public/compiled/controllers/entries/dream_field_controller.js
    - public/compiled/controllers/entries/dream_stream_controller.js
    - public/compiled/controllers/entries/newedit_entry_controller.js
    - public/compiled/controllers/entries/books_controller.js
    - public/compiled/controllers/entries/show_entry_controller.js
    - public/compiled/controllers/users/context_panel_controller.js
    - public/compiled/controllers/users/appearance_panel_controller.js
    
    
    
  shared:
    #- public/javascripts/jquery.hoverIntent.minified.js
    #- public/javascripts/pubsub.js
    #- public/javascripts/rails.js
    #- public/javascripts/jquery.cookie.js
    #- public/javascripts/jquery.placeholder.js
    #- public/javascripts/compiled/modal.js
    #- public/javascripts/compiled/dreamplugs.js
    - public/javascripts/compiled/application.js

  # entries:
  #   - public/javascripts/geo.js
  #   - public/javascripts/dreams.js
  #   - public/javascripts/compiled/follow_hover.js
  #   - public/javascripts/compiled/dreamfield.js
  #   - public/javascripts/tag_stream.js
    
  home:
    - public/javascripts/compiled/dreamplugs.js
    - public/javascripts/compiled/publicstream.js
  
  friends:
    - public/javascripts/compiled/follow_hover.js
  
  new_entry:
    - public/javascripts/browserdetect.js
    - public/javascripts/pubsub.js
    - public/javascripts/compiled/sharing.js
    - public/javascripts/compiled/cookies.js
    
  show_entry:
    - public/javascripts/browserdetect.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/swfobject.js
    - public/javascripts/compiled/showentry.js
    - public/javascripts/compiled/fit_to_content.js

  context_panel:
  #  - public/javascripts/compiled/context_panel.js
  #  - public/javascripts/browserdetect.js
  #  - public/javascripts/dreams.js

  join:
    - public/javascripts/compiled/seedcode.js

  login:
    - public/javascripts/compiled/loginpanel.js
    
  feedback:
    - public/javascripts/compiled/fit_to_content.js
    - public/javascripts/compiled/feedback.js

stylesheets:
  shared:
    - public/stylesheets/compiled/shared.css
    - public/stylesheets/jquery.lightbox-0.5.css
    
  dictionaries:
    - public/stylesheets/compiled/dictionaries.css
    
  imagebank:
    - public/stylesheets/compiled/ib.css
    
    